### ISSUE TITLE
Checkout is not updated before the loading overlay is removed. 

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#45] opened 2020-08-20 10:28 UTC
Related to [#13](https://github.com/Billmate/billmate-checkout-for-woocommerce/issues/13)

When you now update the price of an order in the checkout, for an example when switching between various delivery methods, do you now correctly get the loading overlay and you are not able to interact with the comments. However the loading overlay is done and removed before the checkout has updated itself. It should have updated it's own cost in the checkout as well as the side menu before the overlay is removed.

**Comment by NiklasHogefjord** [comment] 2020-09-01 09:26
How do we accomplish this @OskarOstlund? At the moment we do it in the following sequence:

1. Customer changes shipping method.
2. Billmate Checkout is locked.
3. An update request is sent from Woo to Billmate.
4. When the respons from the request is received `postMessage('update', '*')` is triggered.
5. `postMessage('unlock', '*')` is triggered.

Shouldn't the checkout be ready with the new and updated prices already after the request is received on your end in step 3?

**Comment by MattiasNilsson** [comment] 2020-09-01 11:05
@NiklasHogefjord This is due to cache, so you need to do the 4 and 5 step to achieve full update.

**Comment by NiklasHogefjord** [comment] 2020-09-01 11:27
OK, thanks for the clarification @MattiasNilsson. But how come the price in Billmate Checkout doesn't change until approximately 1 second _after_ step 5?

**Comment by MattiasNilsson** [comment] 2020-09-03 05:28
@NiklasHogefjord It all depends on the load of the server.

**Comment by NiklasHogefjord** [comment] 2020-10-02 13:14
So, that is more of a merchant issue than a plugin issue? Or can we do anything about it @MattiasNilsson ?

**Comment by MattiasNilsson** [comment] 2020-10-22 05:53
@NiklasHogefjord This should be fixed now as the flow has changed?

**Comment by NiklasHogefjord** [comment] 2020-10-22 10:03
No it is not solved in the changed flow @MattiasNilsson. The issue is still here.

According to the docs it looks as I should be able to just do a JS [update](https://billmate.github.io/api-docs/#update) and the iframe will automatically [unlock](https://billmate.github.io/api-docs/#unlock) when the update is done. That doesn't seem to work.

**Comment by MattiasNilsson** [comment] 2020-11-02 07:41
@NiklasHogefjord Is this one still an issue then?

**Comment by NiklasHogefjord** [comment] 2020-11-05 08:54
@MattiasNilsson I don't lock/unlock anymore during update now. Perhaps you can test this and see what you think?

**Comment by OskarOstlund** [comment] 2020-12-22 10:47
This should probably be given a once over. When I tested this could I change the delivery method adding another 10 SEK to the order and while it was loading could I finish placing the order. This caused the checkout thank you message claiming that the order cost 27.50, something that BO and the store both agreed with. However the thank you URL the store directed us to claimed that the order was 17.50 SEK.

**Comment by NiklasHogefjord** [comment] 2020-12-22 11:39
@OskarOstlund & @MattiasNilsson I did a change where we don't lock/unlock BCO during update to avoid the original issue. If you want the plugin to lock down other actions during the update, then you probably need to look into how the unlock event is handled in your system. This is not anything that can be solved only in the plugin from what I can see.

**Comment by MattiasNilsson** [comment] 2020-12-29 07:34
After feedback, we decide to close this one.

**Closed by MattiasNilsson** 2020-12-29 07:34 UTC
