### ISSUE TITLE
Woocommerce 4.4.1 crash.

### ISSUE THREAD

**Issue by anfly0** [Billmate/billmate-checkout-for-woocommerce#57] opened 2020-09-07 16:54 UTC
Woocommerce 4.4.1 causes the checkout plugin to crash.

[Mon Sep 07 16:09:17.919960 2020] [php7:error] [pid 281] [client 89.233.201.220:0] PHP Fatal error:  Uncaught Error: Class 'WC_AJAX' not found in /usr/src/checkout/classes/class-bco-ajax.php:15\nStack trace:\n#0 /usr/src/checkout/billmate-checkout-for-woocommerce.php(113): include_once()\n#1 /usr/src/checkout/billmate-checkout-for-woocommerce.php(96): Billmate_Checkout_For_WooCommerce->include_files()\n#2 /var/www/html/wp-includes/class-wp-hook.php(287): Billmate_Checkout_For_WooCommerce->init('')\n#3 /var/www/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)\n#4 /var/www/html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)\n#5 /var/www/html/wp-settings.php(409): do_action('plugins_loaded')\n#6 /var/www/html/wp-config.php(96): require_once('/var/www/html/w...')\n#7 /var/www/html/wp-load.php(37): require_once('/var/www/html/w...')\n#8 /var/www/html/wp-admin/admin.php(34): require_once('/var/www/html/w...')\n#9 {main}\n  thrown in /usr/src/checkout/classes/class-bco-ajax.php on line 15, referer: https://c37bc972634f.eu.ngrok.io/wp-admin/plugins.php

I have not looked into this any further than this.
But things are working fine with woo-commerce 4.3.0 and the store is completely unavailable with 4.4.1.
@OskarOstlund @MattiasNilsson can one of you confirm this?

**Comment by NiklasHogefjord** [comment] 2020-09-08 05:40
I see what the issue is @anfly0.

We had no check to see if WooCommerce was activated or not in the BCO plugin. The ajax in the plugin is extending WooCommerce's ajax class. When WooCommerce wasn't activated (perhaps during a plugin update in your case) the error was triggered.

I have pushed a commit to master branch now that doesn't trigger any fatal error if WooCommerce isn't active.

**Comment by OskarOstlund** [comment] 2020-09-08 05:43
I was able to make a purchase, activate it, and cancel another as well with version 4.4.1 so it seems to be mostly working, at least on my side.

**Comment by anfly0** [comment] 2020-09-08 07:21
@NiklasHogefjord This seems to have fixed the issue!
@OskarOstlund  Did you have this issue before the latest commit? 
Just wondering if this was only a problem with my test setup.

**Comment by OskarOstlund** [comment] 2020-09-08 07:48
I was able to use the checkout before the commit yes.

**Comment by anfly0** [comment] 2020-09-08 07:53
@OskarOstlund With woocommerce 4.4.1?

**Comment by OskarOstlund** [comment] 2020-09-08 07:54
Yes.

**Comment by NiklasHogefjord** [comment] 2020-09-09 12:16
This is the commit that fixes the issue: 205298b20934113467ec1edf7d04c570811ba553. I'm closing it now. Please re-open it if you still are experiencing problem.

**Closed by NiklasHogefjord** 2020-09-09 12:16 UTC
